source 'http://rubygems.org'
gem 'rails', '3.2.3'

gem 'devise', '>= 2.1.0.rc'
gem 'jquery-rails', '>= 2.0.1'
gem 'rails-backbone', '>= 0.7.1'
gem 'simple_form', '>= 2.0'
gem 'twitter-bootstrap-rails', git: 'git://github.com/seyhunak/twitter-bootstrap-rails.git', branch: 'static'
gem 'thin', '>= 1.3.1'

group :production do
  gem 'pg', '>= 0.13.2'
end

group :development do
  gem 'guard', '>= 0.6.2'
  gem 'guard-bundler', '>= 0.1.3'
  gem 'guard-cucumber', '>= 0.7.5'
  gem 'guard-livereload', '>= 0.4.2'
  gem 'guard-rails', '>= 0.1.0'
  gem 'guard-rspec', '>= 0.7.0'
  gem 'guard-spork', '>= 0.5.2'
  gem 'heroku_san', '>= 2.1.3'
  gem 'spork-rails', '>= 3.2.0'
end

group :development, :test do
  gem 'factory_girl_rails', '>= 3.0'
  gem 'rspec-rails', '>= 2.9.0'
  gem 'sqlite3', '>= 1.3.5'
end

group :test do
  gem 'capybara', '>= 1.1.2'
  gem 'capybara-webkit', '>= 0.11.0'
  gem 'cucumber-rails', '>= 1.3.0'
  gem 'database_cleaner', '>= 0.7.2'
  gem 'email_spec', '>= 1.2.1'
  gem 'simplecov', '>= 0.6.1'
end

group :assets do
  gem 'sass-rails', '3.2.5'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'uglifier', '>= 1.0.3'
end
